### ISSUE TITLE
Add provider.tf at examples folder

### ISSUE THREAD

**Issue by amandakarina** [GoogleCloudPlatform/terraform-google-secured-data-warehouse#204]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave _+1_ or _me too_ comments; they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If the issue is assigned to a user, that user is claiming responsibility for the issue.

### Description

Add provider configuration in examples folder:

```hcl
provider "google" {
  user_project_override = true
  billing_project       = <BOOTSTRAP-PROJECT-ID>
  
  scopes = [
    "https://www.googleapis.com/auth/cloud-platform",
    "https://www.googleapis.com/auth/userinfo.email",
  ]
}
```

### Questions
- Should fixtures keep being executed with terraform service account?
- Should `gcloud` and `curls` commands be able to impersonate some service account?

### References
- https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/client_openid_userinfo

**Comment by marktomlinson1** [comment]
Reused the one from the Secure Foundation example with success:
https://github.com/terraform-google-modules/terraform-example-foundation/blob/master/1-org/envs/shared/providers.tf
