### ISSUE TITLE
Add custom validation rules where possible

### ISSUE THREAD

**Issue by bharathkkb** [GoogleCloudPlatform/terraform-google-secured-data-warehouse#277]
An issue was reported where a user provided bucket name exceeded due to prefix/rand-string being appended. If we know the length of these, we should try to add [custom validation rules](https://www.terraform.io/language/values/variables#custom-validation-rules) where possible to prevent errors at apply time.

```
│ Error: googleapi: Error 400: Use of this bucket name is restricted: 'bkt-cdw-demo-data-ingestion-lanreo-bucket_simple_example-7b683ee9'
, invalid
│
│   with module.secured_data_warehouse.module.data_ingestion.module.data_ingestion_bucket.google_storage_bucket.bucket,
│   on .terraform/modules/secured_data_warehouse.data_ingestion.data_ingestion_bucket/modules/simple_bucket/[main.tf](http://main.tf/) line 17,
 in resource "google_storage_bucket" "bucket":
│   17: resource "google_storage_bucket" "bucket" {
```

**Comment by bharathkkb** [comment]
In some cases it looks like we have two vars used in construction of the name which would not work with custom validation rules https://github.com/GoogleCloudPlatform/terraform-google-secured-data-warehouse/blob/987aaf34ae899edde82b7854530519ea9231e519/modules/data-ingestion/main.tf#L27

**Comment by vfigueiredo-cit** [comment]
Thanks @bharathkkb ! I will take a look.
