### ISSUE TITLE
Remove DLP internal module to use the version 3.77.0 google provider

### ISSUE THREAD

**Issue by amandakarina** [GoogleCloudPlatform/terraform-google-secured-data-warehouse#74]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave _+1_ or _me too_ comments; they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If the issue is assigned to a user, that user is claiming responsibility for the issue.

### Description

With the new version of google provider, the `data_loss_prevention_deidentify_template` resource can handle the `crypto_replace_ffx_fpe_config` and `crypto_deterministic_config`, doing the internal module unnecessary.

**We need to wait the release on github to work on this issue, since the latest release in the repo is different from the latest release in the hashicorp site**

### References
- https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/data_loss_prevention_deidentify_template
- https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/data_loss_prevention_deidentify_template#crypto_replace_ffx_fpe_config
- https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/data_loss_prevention_deidentify_template#crypto_deterministic_config
- https://registry.terraform.io/providers/hashicorp/google/3.77.0
- https://github.com/hashicorp/terraform-provider-google/releases

**Comment by lodotek** [comment]
Any update?
